name: enighet_register
description: aikido grades webapp with firebase backend
version: 0.0.5
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular2: ^2.2.0
  meta: ^1.0.4
  pikaday_datepicker: ^0.8.5
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

#TODO
#Ja, bra om det går att skapa en lista på årets graderingar
#och en summering av hur många genom åren som graderats till de olika graderna.
#Likaså kan det vara bra att varje år kunna skapa en lista på alla dangraderade.
#
#Export till att sätta in i en ordbehandlingsfil.
#
#spara vem som har lagt till, redigirat eller tagit bort data (tillåter bara om användare är inloggad)